export { default as Card } from './Card';
export { default as Declaration } from './Declaration';
export { default as HomeVideo } from './HomeVideo';
export { default as Intro } from './Intro';
export { default as ProductCategories } from './ProductCategories';
export { default as Services } from './Services';
export { default as OurProducts} from './OurProducts';
export { default as ExporterDisclaimer} from './ExporterDisclaimer';
export { default as BrownComponent} from './BrownComponent';
export { default as Paramjit} from './Paramjit';
